version: '3.8'

networks:
  default:
    external: true
    name: mainNetwork

services:
  nginx:
    image: nginx:stable-alpine
    container_name: PLEREAP-NGINXV3
    ports:
      - "7701:80"
    volumes:
      - .:/var/www/ple-reapv3
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: PLEREAP-PHPV3
    volumes:
      - .:/var/www/ple-reapv3
      - ./docker/php/www.conf:/usr/local/etc/php/conf.d/www.conf
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: unless-stopped
